---
# tasks file for hmpps-delius-core-management-server-bootstrap

- name: Set defaults
  set_fact:
    training_scripts_dir: "{{ training_scripts_dir | default('/u01/training') }}"
    app_scripts_dir: "{{ app_scripts_dir | default('/u01/app') }}"

- name: Allow dba group to manage scripts
  file:
    path: '{{ item.path }}'
    state: directory
    recurse: yes
    group: dba
    mode: g+rwxs
  with_items:
    - { path: '{{ training_scripts_dir }}' }
    - { path: '{{ app_scripts_dir }}' }

- name: Generate the training cfg file
  template:
    src: DTR.cfg.j2
    dest: '{{ training_scripts_dir }}/cfg/DTR.cfg'