---

- name: Create script directories with execute permissions for the dba group
  file:
    path: '{{ item.path }}'
    state: directory
    recurse: yes
    group: dba
    mode: 0670
  with_items:
    - { path: '{{ training_scripts_dir }}' }
    - { path: '{{ app_scripts_dir }}' }

- name: Upload script to pull from git
  template:
    src: 'pull-scripts.sh.j2'
    dest: '/usr/bin/pull-scripts'
    mode: u+x

- name: Clone app scripts repo
  become: yes
  become_user: root
  become_method: su
  shell: 'git clone {{ app_scripts_repo }} {{ app_scripts_dir }}'

- name: Clone training scripts repo
  shell: 'git clone {{ training_scripts_repo }} {{ training_scripts_dir }}'