---

- name: Create scripts directories with read-write access for jenkins user
  file:
    path: '{{ item.path }}'
    state: directory
    mode: 0600
  with_items:
    - { path: '{{ training_scripts_dir }}' }
    - { path: '{{ app_scripts_dir }}' }

- name: Upload script to pull from git
  template:
    src: 'pull-scripts.sh.j2'
    dest: '/usr/bin/pull-scripts'
    mode: u+x

- name: Clone app scripts repo
  shell: 'git clone {{ app_scripts_repo }} {{ app_scripts_dir }}'

- name: Clone training scripts repo
  shell: 'git clone {{ training_scripts_repo }} {{ training_scripts_dir }}'

- name: Give execute access to the dba group
  file:
    path: '{{ item.path }}'
    state: directory
    recurse: yes
    group: dba
    mode: 0670
  with_items:
    - { path: '{{ training_scripts_dir }}' }
    - { path: '{{ app_scripts_dir }}' }